server:
  port: 8082
spring:
  application:
    name: hello-service
  datasource:
    url: jdbc:mysql://localhost:3306/vivdb1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml

